// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Если в будущем появятся версии API, можно подключить как в примере:
// import trastpayVersions from "./docs/trastpay_versioned/versions.json";
// import { versionCrumb, versionSelector } from "docusaurus-plugin-openapi-docs/lib/sidebars/utils";

import petstoreSidebar from "./docs/petstore/sidebar";
import trastpaySidebar from "./docs/trastpay/sidebar";
import httpbinSidebar from "./docs/httpbin/sidebar";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // {
    //   type: "html",
    //   value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`,
    //   defaultStyle: true,
    // },
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "category",
      label: "Customization",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "customization",
        },
      ],
    },
  ],
  apis: [
    {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API",
        description:
            "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io",
        slug: "/category/petstore-api",
      },
      items: petstoreSidebar,
    },
    {
      type: "category",
      label: "TrastPay API",
      link: {
        type: "generated-index",
        title: "TrastPay API",
        description: "Документация TrastPay OpenAPI.",
        slug: "/category/trastpay-api",
      },
      items: trastpaySidebar,
    },
    {
      type: "category",
      label: "HTTPBin",
      link: {
        type: "generated-index",
        title: "HTTPBin API",
        slug: "/category/httpbin-api",
      },
      items: httpbinSidebar,
    },
  ],

  // Если понадобится версия, структура будет вот такая:
  // "trastpay-1.0.0": [
  //   {
  //     type: "html",
  //     defaultStyle: true,
  //     value: versionSelector(trastpayVersions),
  //     className: "version-button",
  //   },
  //   {
  //     type: "html",
  //     defaultStyle: true,
  //     value: versionCrumb(`v1.0.0`),
  //   },
  //   {
  //     type: "category",
  //     label: "TrastPay",
  //     link: {
  //       type: "generated-index",
  //       title: "TrastPay API (v1.0.0)",
  //       slug: "/category/trastpay-api-1.0.0",
  //     },
  //     items: require("./docs/trastpay_versioned/1.0.0/sidebar.js"),
  //   },
  // ],
};

export default sidebars;
